"""added hashed_password filed to the attendee table

Revision ID: 1df1b3e7ab2c
Revises: 5934f4ccd1ef
Create Date: 2025-03-28 14:06:31.547395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df1b3e7ab2c'
down_revision: Union[str, None] = '5934f4ccd1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendees', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendees', 'hashed_password')
    # ### end Alembic commands ###
