"""attndee table changes for user authentication

Revision ID: 5934f4ccd1ef
Revises: f198cf2ea2b8
Create Date: 2025-03-28 13:27:11.379727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5934f4ccd1ef'
down_revision: Union[str, None] = 'f198cf2ea2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendees', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('attendees', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('attendees', 'phone_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('attendees', 'event_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendees', 'event_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('attendees', 'phone_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('attendees', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('attendees', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
