"""removed_index

Revision ID: f198cf2ea2b8
Revises: 723b14ef2f21
Create Date: 2025-03-27 00:41:45.914692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f198cf2ea2b8'
down_revision: Union[str, None] = '723b14ef2f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendees_attendee_id', table_name='attendees')
    op.drop_index('ix_events_event_id', table_name='events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_event_id', 'events', ['event_id'], unique=False)
    op.create_index('ix_attendees_attendee_id', 'attendees', ['attendee_id'], unique=False)
    # ### end Alembic commands ###
